# Generated by Django 5.0 on 2026-07-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_apellido_and_more'),
        ('productos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo', models.CharField(help_text='Ej: EFECTIVO, MERCADOPAGO', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pedido')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('En Camino', 'En Camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20, verbose_name='Estado del pedido')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Notas de entrega')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('direccion_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.direccionentrega', verbose_name='Dirección de entrega')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.metodopago', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia_comprobante', models.CharField(blank=True, max_length=100)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100)),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=100)),
                ('mercadopago_status', models.CharField(blank=True, max_length=50)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente de Verificación / Cobro'), ('Aprobado', 'Aprobado / Pagado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=30)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.metodopago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pago de Pedido',
                'verbose_name_plural': 'Pagos de Pedidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
    ]
