# Generated by Django 5.0 on 2026-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagopedido',
            name='tarjeta_titular',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titular de la tarjeta'),
        ),
        migrations.AddField(
            model_name='pagopedido',
            name='tarjeta_ultimos_4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos tarjeta'),
        ),
    ]
