from apps.logistica.models import Zona, Barrio

barrios = [
    "VILLA DON SANTIAGO", "PARQUE AUTODROMO", "CRISTO REY", "VILLA ELBA", "VILLA GHIO", "VILLA LUISA",
    "PICCILLI", "VILLA CORTES", "VILLA ODORICO", "PERRANDO", "VILLA ALTA", "VILLA MARIA",
    "VILLA 25 DE MAYO Y PEZZINI", "VILLA ADELANTE", "VILLA ALVEAR", "BARRIO SAN JAVIER", "VILLA JUAN DE GARAY",
    "VILLA SEITOR", "VILLA PEGORARO", "PROVINCIAL", "FOECYT", "ESPAÑA", "PROVINCIAS UNIDAS", "POLICIAL",
    "SANTA BARBARA", "JESUS MARIA", "SANTA RITA", "LOS CISNES", "VILLA DON ENRIQUE", "SANTA INES", "BORRINI",
    "SAN CAYETANO", "VILLA DEL OESTE", "VILLA ERCILIA", "MONSEÑOR DE CARLO", "BELGRANO", "VILLA RIO ARAZA",
    "VILLA DEL PARQUE", "VILLA PROGRESO", "SAN MIGUEL", "MALVINAS", "VILLA NUEVA", "JUAN DOMINGO PERON",
    "DON ALBERTO", "LOS PINOS", "ITALIA", "RAOTA", "BARBERAN", "BITTEL DEOLINDO F.", "ARAMBURU",
    "VILLA BARBETTI", "JORGE NEWBERY", "VIRGEN DEL LOURDES", "VELEZ SARFIELD", "VILLA CENTENARIO",
    "PARQUE INDEPENDENCIA", "LLAPONAGAT", "ITATI", "VILLA CENTRAL NORTE", "VILLA SAN JUAN", "GRAL. OBLIGADO",
    "VILLA FEDERAL", "VILLA MINISTRO RAWSON", "VILLA ELISA", "JUAN BAUTISTA ALBERDI", "NAZARETH", "GÜIRALDES",
    "U.P.C.P.", "17 DE OCTUBRE", "HIPOLITO IRIGOYEN (CH. 208)", "FORTINES ARGENTINOS", "DUARTE MARIA EVA",
    "VALUSSI", "SAN FERNANDO", "HIPOLITO IRIGOYEN (CH. 204)", "VILLA GOB. LUZURIAGA A", "VILLA AEROPUERTO",
    "VILLA MARIANO MORENO", "VILLA TTE. SAAVEDRA", "LA FABRIL", "ROGER BALET", "SAN ANTONIO", "VILLA EL DORADO",
    "VILLA PALERMO I", "FACUNDO", "VILLA PALERMO II", "VILLA DON ANDRÉS", "VILLA CHICA", "VILLA DON RAFAEL",
    "VILLA DEL CARMEN", "VILLA LOS LIRIOS", "VILLA DONOVAN", "VILLA GRAL. MITRE", "VILLA JARDIN", "LA LIGURIA",
    "PADRE FYRNYS", "LOS TRONCOS", "VILLA PUPPO", "ASUNCION", "VILLA SAN MARTIN", "VILLA ALTABE",
    "VILLA CAMORS", "PAYKIN", "SANTA CATALINA", "VILLA PROSPERIDAD", "DON BOSCO", "VARGAS II", "VILLA FABIANA",
    "VILLA UNIVERSIDAD", "VILLA GONZALITO", "VILLA MIRANDA GALLINO", "VILLA AVALOS", "VILLA STO. DOMINGO",
    "B. STA. CLARA", "EL BOLSON", "VILLA RIO NEGRO", "ATLANTICO SUR", "TOBA", "AMERICA", "CENTRO",
    "SANTA LUCIA", "MUJERES ARGENTINAS", "VILLA ENCARNACION DE JESUS", "VILLA LIBERTAD", "GOLF. CLUB",
    "SAN VALENTIN", "EL TIMBO", "VILLA EL TALA", "VILLA MARIN", "VILLA CAMILA", "VILLA LA ISLA", "LA FRANCE",
    "ZONA MONTE ALTO", "13 de DICIEMBRE", "FAVALORO RENE GERONIMO", "VILLA PARQUE FAVRE", "JUANA AZURDUY",
    "CARAGUATA", "VILLA FABIANA NORTE", "GREGORIO COLUSSI", "BEATRIZ \"BETTINA\" VAZQUEZ", "LOS FRESNOS",
    "ZONA TERMINAL", "VILLA GOB. LUZURIAGA B", "VILLA AYELEN", "LOS LAPACHOS DE ZONA NORTE", "HUMBERTO BARBETTI",
    "PAPA FRANCISCO"
]

# Create a default zone for unassigned barrios
zona_default, _ = Zona.objects.get_or_create(
    nombre="Sin Asignar",
    defaults={'descripcion': 'Zona por defecto para barrios sin asignar'}
)

for b_name in barrios:
    Barrio.objects.get_or_create(
        nombre=b_name,
        ciudad="Resistencia",
        defaults={'zona': zona_default}
    )

print(f"Se crearon o actualizaron {len(barrios)} barrios con éxito.")
