# Generated by Django 5.0 on 2026-07-29 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
            },
        ),
        migrations.CreateModel(
            name='RolEmpleado',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol de Empleado',
                'verbose_name_plural': 'Roles de Empleados',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='logistica.rolempleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('En curso', 'En curso'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='logistica.camion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='logistica.empleado')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='logistica.zona')),
            ],
            options={
                'verbose_name': 'Hoja de Ruta',
                'verbose_name_plural': 'Hojas de Ruta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleHojaRuta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_ref', models.CharField(blank=True, help_text='Referencia temporal al pedido hasta que exista el modelo Pedido', max_length=100)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de entrega (texto libre hasta integrar Direccion_entrega)', max_length=255)),
                ('cliente_nombre', models.CharField(blank=True, help_text='Nombre del cliente para identificación rápida', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visita dentro de la ruta (menor = primero)')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Reprogramado', 'Reprogramado')], default='Pendiente', max_length=20)),
                ('nota_entrega', models.TextField(blank=True)),
                ('hora_registro', models.DateTimeField(blank=True, null=True)),
                ('hoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.hojaruta')),
            ],
            options={
                'verbose_name': 'Detalle de Ruta',
                'verbose_name_plural': 'Detalles de Ruta',
                'ordering': ['orden'],
            },
        ),
    ]
