# Generated by Django 5.0 on 2026-07-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zona',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zona',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zona',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zona',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zona',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
    ]
