# Generated by Django 5.0 on 2026-07-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_zona_jueves_zona_lunes_zona_martes_zona_miercoles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='barrios',
            field=models.TextField(blank=True, help_text='Barrios que abarca esta zona (ej: Centro, San Martín, Belgrano)', verbose_name='Barrios incluidos'),
        ),
        migrations.AddField(
            model_name='zona',
            name='ciudad',
            field=models.CharField(blank=True, default='Presidencia Roque Sáenz Peña', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
