# Generated by Django 5.0 on 2026-07-31 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_direccionentrega_zona'),
        ('logistica', '0003_zona_barrios_zona_ciudad_alter_zona_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallehojaruta',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='barrios',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='miercoles',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='viernes',
        ),
        migrations.AddField(
            model_name='detallehojaruta',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_ruta', to='clientes.direccionentrega', verbose_name='Dirección de Entrega'),
        ),
        migrations.AddField(
            model_name='detallehojaruta',
            name='direccion_texto',
            field=models.CharField(blank=True, help_text='Dirección en texto si no hay una vinculada', max_length=255),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ruta', to='logistica.camion'),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ruta', to='logistica.empleado'),
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(default='Resistencia', max_length=100)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barrios_asociados', to='logistica.zona')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RutaReparto',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Ruta Norte - Lunes', max_length=100)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('camion_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_default', to='logistica.camion')),
                ('empleado_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_default', to='logistica.empleado')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='logistica.zona')),
            ],
            options={
                'verbose_name': 'Ruta de Reparto',
                'verbose_name_plural': 'Rutas de Reparto',
                'ordering': ['dia_semana', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='ruta_reparto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ruta', to='logistica.rutareparto', verbose_name='Ruta de Reparto'),
            preserve_default=False,
        ),
    ]
