# Generated by Django 5.0 on 2026-07-31 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolEmpleado',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol de empleado',
                'verbose_name_plural': 'Roles de empleado',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('celular', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='empleados.rolempleado', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
