# Generated by Django 5.0 on 2026-07-29 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('tipo_cliente', models.CharField(choices=[('Normal', 'Normal'), ('Premium', 'VIP / Premium')], default='Normal', max_length=10, verbose_name='Tipo de cliente')),
                ('bidones_prestados', models.PositiveIntegerField(default=0, verbose_name='Bidones prestados')),
                ('permite_fiado', models.BooleanField(default=False, help_text='Habilitado automáticamente para clientes Premium', verbose_name='Permite fiado')),
                ('notas_internas', models.TextField(blank=True, help_text='Visible solo para Admin/Vendedor', verbose_name='Notas internas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['usuario__last_name', 'usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=150, verbose_name='Calle')),
                ('altura', models.CharField(max_length=10, verbose_name='Altura / Número')),
                ('piso_depto', models.CharField(blank=True, help_text='Ej: "2°B", "PB derecha"', max_length=30, verbose_name='Piso / Depto')),
                ('desc_seguridad', models.TextField(blank=True, help_text='SOLO visible para Admin, Vendedor y Repartidor asignado — RF-03', verbose_name='Nota de seguridad')),
                ('coordenadas', models.CharField(blank=True, help_text='Para futura integración con mapas', max_length=60, verbose_name='Coordenadas (lat,lng)')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direcciones_clientes', to='logistica.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Dirección de entrega',
                'verbose_name_plural': 'Direcciones de entrega',
                'ordering': ['-es_principal', 'calle', 'altura'],
            },
        ),
        migrations.CreateModel(
            name='TelefonoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=25, verbose_name='Número')),
                ('desc_relacion', models.CharField(help_text='Ej: "Titular", "Cónyuge", "Hijo", "Vecino de confianza"', max_length=100, verbose_name='Relación')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Teléfono de contacto',
                'verbose_name_plural': 'Teléfonos de contacto',
                'ordering': ['-es_principal', 'desc_relacion'],
            },
        ),
    ]
