# Generated by Django 5.0 on 2026-07-29 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_contacto',
            field=models.EmailField(blank=True, help_text='Opcional — para clientes sin cuenta web', max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario'),
        ),
    ]
