# Generated by Django 5.0 on 2026-07-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionentrega',
            name='barrio',
            field=models.CharField(blank=True, help_text='Ej: Centro, San Martín, Belgrano...', max_length=100, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='ciudad',
            field=models.CharField(blank=True, default='Presidencia Roque Sáenz Peña', max_length=100, verbose_name='Ciudad / Localidad'),
        ),
    ]
