# Generated by Django 5.0 on 2026-07-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_direccionentrega_barrio_direccionentrega_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionentrega',
            name='zona',
        ),
    ]
