# Generated by Django 5.0 on 2026-07-31 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_direccionentrega_zona'),
        ('logistica', '0004_remove_detallehojaruta_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionentrega',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direcciones_clientes', to='logistica.barrio', verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='direccionentrega',
            name='ciudad',
            field=models.CharField(blank=True, default='Resistencia', max_length=100, verbose_name='Ciudad / Localidad'),
        ),
    ]
